# This is a basic workflow to help you get started with Actions

name: AgriQuesAnsCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  agriqa:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install and start Ollama on Ubuntu Runner VM
      - name: Install Ollama
        run: curl -fsSL https://ollama.com/install.sh | sudo sh

      - name: Start Ollama Server
        run: |
            ollama serve &
            sleep 3
            curl -s http://localhost:11434    

      - name: Pull nomic embeddings model
        run: ollama pull nomic-embed-text:latest

      - name: Pull gemma3 model
        run: ollama pull gemma3:latest
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Create vectorstore
        run: python src/mqr/agri_unece_create_vs.py
